pom.xml
src/main/java/io/zeebe/exporter/proto/RecordTransformer.java
src/main/proto/schema.proto
src/test/java/io/zeebe/exporter/proto/RecordTransformTest.java

- add workflow key to IncidentRecord
BREAKING CHANGE:
- remove raft related records
- remove raftTerm from RecordMetadata and renumbered remaining fields

feat(project): update to Zeebe 0.18.0

---

pom.xml
src/main/java/io/zeebe/exporter/proto/RecordTransformer.java
src/main/proto/schema.proto
src/test/java/io/zeebe/exporter/proto/RecordTransformTest.java

* rename fields to align with the record properties
* add missing fields from records
* move job headers into the job record
* new enums for record type, value, type, update semantics

chore(proto): update to Zeebe 0.19.0

---

.ci/scripts/github-release.sh
Jenkinsfile
pom.xml
src/main/java/io/zeebe/exporter/proto/RecordTransformer.java
src/main/proto/schema.proto
src/test/java/io/zeebe/exporter/proto/RecordTransformTest.java

* new BPMN element type: CALL_ACTIVITY
* new workflow instance record properties
* new value type: WORKFLOW_INSTANCE_RESULT
* new record for workflow instance result

chore(POM): migrate to Zeebe 0.22.0-alpha1

---

Jenkinsfile

Uses feature introduced with https://github.com/zeebe-io/zeebe-jenkins-shared-library/pull/3 as showcase for CI-affine persons of Zeebe team @korthout @npepinpe @Zelldon.
Please review and merge at your discretion :+1:
Related to INFRA-1948

chore(ci): demonstrate adoption of new mavenPodspec helper of zeebe-jenkins-shared-library

---

src/main/java/io/zeebe/exporter/proto/RecordTransformer.java
src/main/proto/schema.proto
src/test/java/io/zeebe/exporter/proto/RecordTransformTest.java

* add new property `isInterrupting` for message subscriptions and process message subscriptions
closes #105

feat(proto): add `isInterrupting` for subscriptions

---

src/main/java/io/zeebe/exporter/proto/RecordTransformer.java
src/main/proto/schema.proto
src/test/java/io/zeebe/exporter/proto/RecordTransformTest.java

* extend the deployment record by decision requirements and decision metadata
* add a duplicated property to the process metadata

Deployment with DMN metadata

---

pom.xml
src/main/java/io/zeebe/exporter/proto/RecordTransformer.java
src/main/proto/schema.proto
src/test/java/io/zeebe/exporter/proto/RecordTransformTest.java

Dump Zeebe from `8.0.6` to `8.1.8`.
Add new records: `process instance modification` + `checkpoint`.
closes #203

feat: Update to Zeebe 8.1

---

src/main/java/io/zeebe/exporter/proto/RecordTransformer.java
src/main/proto/schema.proto
src/test/java/io/zeebe/exporter/proto/RecordTransformTest.java

Add the property for the BPMN process id to the variable record.

feat: Add BPMN process id to variable record

---

pom.xml

Update Maven parent pom and switch to the Camunda community parent.

build: Switch to Camunda community parent

---

pom.xml
src/main/java/io/zeebe/exporter/proto/RecordTransformer.java
src/main/proto/schema.proto
src/test/java/io/zeebe/exporter/proto/RecordTransformTest.java

Dump `Zeebe` from `8.1.8` to `8.2.0-alpha4`.
Add the new value types to the protocol.

feat: Update to Zeebe 8.2.0-alpha4

---

src/main/java/io/zeebe/exporter/proto/RecordTransformer.java
src/main/proto/schema.proto
src/test/java/io/zeebe/exporter/proto/RecordTransformTest.java

Add event type for process instance record. so that as a consumer of the record stream, you can distinguish the type of event that is processed. 
Closes #237

feat: Add event type to process instance record

---

pom.xml
src/main/java/io/zeebe/exporter/proto/RecordTransformer.java
src/main/proto/schema.proto
src/test/java/io/zeebe/exporter/proto/RecordTransformTest.java

Add new signal and signal subscription records to the protocol.
```protobuf
message SignalRecord {
RecordMetadata metadata = 1;
string signalName = 2;
google.protobuf.Struct variables = 3;
}
message SignalSubscriptionRecord {
RecordMetadata metadata = 1;
string signalName = 2;
int64 processDefinitionKey = 3;
string bpmnProcessId = 4;
string catchEventId = 5;
int64 catchEventInstanceKey = 6;
}
```

Update Zeebe to 8.2.0-rc1

---

pom.xml

Dump Zeebe from `8.2.0-rc1` to `8.2.0`.

deps: dump zeebe to 8.2.0

---

src/main/java/io/zeebe/exporter/proto/RecordTransformer.java
src/main/proto/schema.proto
src/test/java/io/zeebe/exporter/proto/RecordTransformTest.java

- Add form record to schema.
- Extend deployment record by form metadata.
closes #344

feat: Add form record

---

src/main/java/io/zeebe/exporter/proto/RecordTransformer.java
src/main/proto/schema.proto
src/test/java/io/zeebe/exporter/proto/RecordTransformTest.java

* Add the resource deletion record to the schema.
closes #340

feat: Add resource deletion record

---

src/main/java/io/zeebe/exporter/proto/RecordTransformer.java
src/main/proto/schema.proto
src/test/java/io/zeebe/exporter/proto/RecordTransformTest.java

Add the user task record to the schema.
related to #341

feat: Add user task record

---

.github/workflows/build.yml
.github/workflows/deploy.yml

Remove cache from GitHub workflow.

ci: Remove cache from GitHub workflow

---

src/main/java/io/zeebe/exporter/proto/ProtobufUtil.java
src/test/java/io/zeebe/exporter/proto/ProtobufUtilTest.java

Add a utility to transform a struct into a Java map object.

feat: Add util to transform a struct into a map

---

src/main/java/io/zeebe/exporter/proto/RecordTransformer.java
src/main/proto/schema.proto
src/test/java/io/zeebe/exporter/proto/RecordTransformTest.java

Add new record for compensation subscriptions with properties from Zeebe 8.5 ([ref](https://github.com/camunda/zeebe/blob/8.5.0/zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/compensation/CompensationSubscriptionRecord.java)).
closes #343

feat: Add compensation subscription record

---

src/main/java/io/zeebe/exporter/proto/RecordTransformer.java
src/main/proto/schema.proto
src/test/java/io/zeebe/exporter/proto/RecordTransformTest.java

* Add new record for escalation with properties from Zeebe 8.5 ([ref](https://github.com/camunda/zeebe/blob/8.5.0/zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/escalation/EscalationRecord.java)).
closes #339

feat: Add escalation record
